KhadimHussainDev/TheExportersLoom-Apis

- package-lock.json
- src/users/users.module.ts
- Registered ResetTokenRepository in UsersModule to resolve DI issue
- Fixed startup error caused by missing repository
- Closes #3
> fix(users-service): resolve missing ResetTokenRepository dependency

- package-lock.json
- package.json
- src/main.ts
- src/users/dto/create-user.dto.ts
- src/users/users.controller.ts
- Added validation for signup request body.
- Handled missing request body to prevent crashes.
- Improved error handling for invalid inputs.
Closes #5
> fix: resolve signup validation crash

- package-lock.json
- package.json
- src/users/dto/reset-password.dto.ts
- src/users/dto/verify-email-token.dto.ts
- src/users/entities/email-verification.entity.ts
- src/users/services/mail.service.ts
- src/users/users.controller.ts
- src/users/users.module.ts
- src/users/users.service.ts
- Implemented `requestEmailVerification` method to send a 6-digit verification code to the user’s email.
- Created `verifyEmail` method to validate the code and update the email verification status.
- Added `MailService` with `sendMail` functionality using nodemailer.
- Introduced `VerifyEmailDto` to handle verification code and email validation.
- Updated `EmailVerificationToken` entity to store verification codes with expiry dates.
> feat: add email verification service and API endpoints

- .env.example
- Added EMAIL_USER and EMAIL_PASS for email authentication setup.
- Added CLIENT_URL for frontend link reference.
- Updated .env.example to include necessary environment variables for email verification.
> chore: add email configuration variables to .env.example

- package-lock.json
- package.json
- src/app.module.ts
- src/messages/chat.gateway.ts
- src/messages/dto/create-message.dto.ts
- src/messages/message.entity.ts
- src/messages/messages.controller.ts
- src/messages/messages.module.ts
- src/messages/messages.service.ts
- Added WebSocket gateway for real-time chat functionality
- Implemented message handling with `sendMessage` event
- Users join rooms based on sender and receiver IDs
- Messages are saved to the database and emitted to the appropriate room
- Ensured users join rooms only if they are not already in them
- Broadcast messages to all clients in the room except the sender
- Added error handling and logging for message creation
- Updated DTOs and entity definitions for message structure
> feat: Implement complete chat messaging logic

- src/app.module.ts
- Updated TypeORM configuration in `app.module.ts` to include all entity files
- Ensured that the `entities` array correctly matches all `.entity.ts` and `.entity.js` files
-
> fix: Ensure all entities are included in TypeORM configuration

- src/messages/chat.gateway.ts
- Added logic to join rooms by user id
- Removed logic to create common room between two users -Improved room creation for notifications
> feat: Enhance chat gateway functionality

- src/notifications/dtos/create-notification.dto.ts
- src/notifications/entities/notification.entity.ts
- src/notifications/gateway/notification.gateway.ts
- src/notifications/notification.gateway.ts
- src/notifications/notifications.controller.ts
- src/notifications/notifications.module.ts
- src/notifications/notifications.service.ts
- Added Notification entity to represent notifications in the database
- Created DTO for creating notifications
- Implemented NotificationsService to handle business logic for notifications
- Added NotificationsController to handle HTTP requests related to notifications
- Integrated WebSocket gateway for real-time notification updates
- Added endpoints for creating notifications, retrieving notifications for a user, and marking notifications as read
> feat: Implement notification logic

- src/scripts/seeder.controller.ts
- src/scripts/seeder.module.ts
- src/scripts/seeder.service.ts
- Moved seeder logic from `seeder.ts` to `seeder.service.ts`
- Created `SeederService` to handle data population logic
- Added `SeederController` to expose an endpoint for triggering data population
- Ensured environment variables are loaded correctly
- Added error handling and logging for data population process
> feat: Refactor seeder logic and add endpoint to trigger data population

- src/app.module.ts
- src/auth/jwt.strategy.ts
- src/bid/bid.module.ts
- src/bid/bid.service.ts
- src/bid/entities/bid.entity.ts
- src/machines/entities/machine.entity.ts
- src/machines/machine.controller.ts
- src/order/dtos/create-order.dto.ts
- src/order/dtos/update-order.dto.ts
- src/order/entities/order.entity.ts
- src/order/order.controller.ts
- src/order/order.module.ts
- src/order/order.service.ts
- src/scripts/seeder.service.ts
- src/scripts/seeder.ts
- src/users/entities/user.entity.ts
- Added Order entity with relationships to Bid,  User, and Machine entities
- Created OrderService to handle CRUD operations for orders
- Developed OrderController to expose endpoints for managing orders
- Ensured proper validation and data transfer using DTOs for creating and updating orders
- Configured OrderModule to include necessary imports and providers
> feat: Implement Order module with controller, service, and entity

- src/app.module.ts
- src/machines/entities/machine.entity.ts
- src/order/entities/order.entity.ts
- src/order/order.module.ts
- src/reviews/dtos/create-review.dto.ts
- src/reviews/dtos/update-review.dto.ts
- src/reviews/entities/reviews.entity.ts
- src/reviews/reviews.controller.ts
- src/reviews/reviews.module.ts
- src/reviews/reviews.service.ts
- src/users/entities/user.entity.ts
- Added Review entity with relationships to Order, User, and Machine entities
- Created ReviewService to handle CRUD operations for reviews
- Developed ReviewController to expose endpoints for managing reviews
- Ensured proper validation and data transfer using DTOs for creating and updating reviews
- Configured ReviewModule to include necessary imports and providers
- Updated Order, User, and Machine entities to establish bidirectional relationships with Review entity
> feat: Implement Reviews module with entity, service, and controller

- src/main.ts
- src/users/dto/create-user.dto.ts
- src/users/entities/user-profile.entity.ts
- src/users/entities/user.entity.ts
> Update signup API to accept only userType, email, and password. 

- src/users/users.controller.ts
- src/users/users.service.ts
- Added `statusCode` property to all response objects in `users.controller.ts`
- Updated error handling to include `statusCode` in the response
This change ensures that the frontend can reliably check the `statusCode` property for all responses.
> Ensure consistent response format across all user controller methods

- src/cost-estimation/system-content.txt
- Added new attributes to the JSON template for cost estimation
- Updated extraction rules to ensure accurate data extraction from input prompts
- Included default values for attributes not explicitly stated in the prompt
This change ensures a more comprehensive and accurate extraction process for cost estimation.
> Update JSON template and extraction rules in system-content.txt

- src/modules/cutting module/cutting.controller.ts
- src/modules/cutting module/cutting.module.ts
- src/modules/cutting module/cutting.service.ts
- src/modules/cutting module/dto/update-cutting.dto.ts
- src/modules/cutting module/entities/cutting.entity.ts
- src/modules/fabric-price module/dto/create-fabric-pricing.dto.ts
- src/modules/fabric-price module/fabric-pricing.controller.ts
- src/modules/fabric-price module/fabric-pricing.module.ts
- src/modules/fabric-price module/fabric-pricing.service.ts
- src/modules/fabric-quantity-module/dto/create-fabric-quantity.dto.ts
- src/modules/fabric-quantity-module/dto/update-fabric-quantity.dto.ts
- src/modules/fabric-quantity-module/fabric-quantity.controller.ts
- src/modules/fabric-quantity-module/fabric-quantity.module.ts
- src/modules/fabric-quantity-module/fabric-quantity.service.ts
- src/modules/logo-printing module/dto/create-logo-printing.dto.ts
- src/modules/logo-printing module/dto/update-logo-printing.dto.ts
- src/modules/logo-printing module/entities/logo-printing.entity.ts
- src/modules/logo-printing module/logo-printing.controller.ts
- src/modules/logo-printing module/logo-printing.service.ts
- src/modules/packaging module/packaging.controller.ts
- src/modules/packaging module/packaging.service.ts
- src/modules/stitching module/stitching.controller.ts
- src/modules/stitching module/stitching.service.ts
- src/project/dto/create-project.dto.ts
- src/project/dto/update-project.dto.ts
- src/project/entities/project.entity.ts
- src/project/project.controller.ts
- src/project/project.service.ts
I have made all necessary changes and updates to the CRUD APIs for the project and related modules. Everything has been tested. Please review the updates.
> Project and modules

- src/reviews/reviews.controller.ts
- src/reviews/reviews.service.ts
- Ensure reviews cannot be posted on orders that are in pending state.
- Handle errors properly by returning structured error responses.
> fix: resolve issue #37 - prevent reviews on pending orders

- src/app.module.ts
- src/product-configuration/dto/get-subcategories.dto.ts
- src/product-configuration/product-configuration.controller.ts
- src/product-configuration/product-configuration.module.ts
- src/product-configuration/product-configuration.service.ts
- Implemented APIs to fetch distinct logo positions, printing methods, categories, subcategories, and product types
> feat: add product configuration APIs

- src/users/users.service.ts
- Ensure database queries for login are case-insensitive
Fixes #31
> fix(auth): make email case-insensitive during sign-in

- src/auth/auth.service.ts
- src/auth/google.strategy.ts
- src/modules/fabric-quantity-module/dto/create-fabric-quantity.dto.ts
- src/modules/fabric-quantity-module/dto/fabricSizeDetails.dto.ts
- src/modules/fabric-quantity-module/dto/update-fabric-quantity.dto.ts
- src/modules/fabric-quantity-module/fabric-quantity.service.ts
- src/modules/logo-printing module/dto/create-logo-printing.dto.ts
- src/modules/logo-printing module/dto/logo-details.dto.ts
- src/modules/logo-printing module/dto/update-logo-printing.dto.ts
- src/modules/logo-printing module/entities/logo-printing.entity.ts
- src/modules/logo-printing module/logo-printing.controller.ts
- src/modules/logo-printing module/logo-printing.service.ts
- src/project/dto/create-project.dto.ts
- src/project/dto/update-project.dto.ts
- src/project/entities/project.entity.ts
- src/project/project.service.ts
- src/users/users.service.ts
- Renamed `user_id` to `userId` in authentication and related services for consistency.
- Updated fabric quantity handling by renaming `quantityRequired` to `quantity` across multiple services and DTOs.
- Adjusted related logic in project and logo printing services to reflect these changes.
- Cleaned up unused DTO definitions to streamline the codebase.
> refactor: standardize user and fabric quantity attributes

- src/order/order.module.ts
- src/order/order.service.ts
- src/reviews/reviews.controller.ts
- src/reviews/reviews.module.ts
- src/reviews/reviews.service.ts
- src/users/dto/update-users.dto.ts
- src/users/entities/user-profile.entity.ts
- src/users/users.controller.ts
- src/users/users.module.ts
- src/users/users.service.ts
- Updated `OrderModule` and `ReviewsModule` to use `forwardRef` for circular dependency resolution.
- Added new endpoints in `ReviewsController` to retrieve all reviews of a user and calculate the user's average rating.
- Enhanced `UsersService` to include user profile retrieval with average rating.
- Updated `UserProfile` entity and `UpdateUserDto` to accommodate new `bio` and `picture` fields.
> refactor: enhance module dependencies and add user review features

- src/order/order.controller.ts
- src/order/order.service.ts
- src/project/project.controller.ts
- src/project/project.service.ts
- Introduced new endpoints in `OrderController` for retrieving overall and user-specific order statistics.
- Enhanced `OrderService` with methods to calculate order statistics and fetch orders by user ID.
- Updated `ProjectController` to include endpoints for project statistics, both overall and user-specific.
- Added corresponding methods in `ProjectService` to calculate project statistics and fetch projects by user ID.
> feat: add order and project statistics endpoints

- src/auth/jwt.strategy.ts
- src/bid/bid.controller.ts
- src/bid/dto/update-bid.dto.ts
- src/machines/machine.service.ts
- src/modules/fabric-price module/fabric-pricing.controller.ts
- src/modules/fabric-price module/fabric-pricing.service.ts
- src/modules/logo-printing module/dto/logo-details.dto.ts
- src/modules/logo-printing module/logo-printing.service.ts
- src/project/entities/project.entity.ts
- src/project/project.service.ts
- Corrected the terminology for 'oversized front' to 'oversize front' in both the service and DTO files.
- Introduced a new private method in `ProjectService` to generate project names based on sizes and shirt type, improving project entity creation and updates.
- Added a `name` field to the `Project` entity to store the generated project name.
- Updated project transformation logic to utilize the generated name or fallback appropriately.
> fix: standardize logo printing terminology and enhance project name generation

- src/machines/machine.service.ts
- src/order/order.module.ts
- src/recommendBids/recommendBids.controller.ts
- src/recommendBids/recommendBids.service.ts
- src/recommendBids/recommmendBids.module.ts
- src/reviews/reviews.module.ts
Implemented the bid recommendation system to suggest relevant bids to manufacturers based on machine registered and exporter history.  
- Added logic to fetch bids matching the manufacturer's machine types.  
- Integrated past collaboration data to prioritize bids.  
- Incorporated exporter reviews and ratings for better recommendations.
> feat: implement bid recommendation system  
